version: '3'
services:
  app:
    build:
      context: .  # Points to the root directory
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"

  worker:
    build:
      context: .  # Points to the root directory
      dockerfile: Dockerfile.worker
